# Generated by Django 4.0.1 on 2022-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='movies_thumbnails'),
        ),
    ]
