# Generated by Django 4.0.1 on 2022-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie_default.jpg', upload_to='movies_thumbnails'),
        ),
    ]
